version: '2'
services:
  db:
    container_name: amd_catalog_db
    image: mysql:5.6.35
    environment:
      MYSQL_DATABASE: berepublic_sf3
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD:  root
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql
  web:
    build:
      context: docker/web
    ports:
      - "8080:80"
    tty: true
    depends_on:
      - db
    volumes:
      - /Users/bronsoms/Sites/sf3-docker/:/var/www/html
volumes:
  database:
    driver: "local"
