version: '2'
services:
  db:
    image: mysql:5.6.35
    environment:
      MYSQL_DATABASE: berepublic_sf3
      MYSQL_USER: berepublic
      MYSQL_PASSWORD: berepublic
      MYSQL_ROOT_PASSWORD:  berepublic
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql
  web:
    build:
      context: docker
    ports:
      - "8080:80"
    tty: true
    depends_on:
      - db
    volumes:
      - .:/var/www
volumes:
  database:
    driver: "local"
